import type { Metadata } from 'next'
import { PrimeReactProvider } from 'primereact/api'
import 'primereact/resources/themes/saga-blue/theme.css'
import './globals.css'
import { Header } from '@/components/header'
import Footer from '@/components/footer'
import { AuthProvider } from '@/context/AuthContext'

export const metadata: Metadata = {
  title: 'Travelopia - Khám phá Đà Nẵng',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <PrimeReactProvider>
            {/* TODO: Sau này sửa component Header để dùng useAuth() thay vì truyền props cứng */}
            <Header isAuthenticated={false} />
            {/*main chỉ chứa nội dung chính thay đổi */}
            <main className="min-h-screen bg-brand-bg">{children}</main>
            <Footer />
          </PrimeReactProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
