import type { Metadata } from 'next'
import { PrimeReactProvider } from 'primereact/api'
// import 'primeicons/primeicons.css'
import './globals.css'

export const metadata: Metadata = {
  title: 'Travelopia - Khám phá Đà Nẵng',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <PrimeReactProvider>
          <main className="min-h-screen bg-brand-bg">{children}</main>
        </PrimeReactProvider>
      </body>
    </html>
  )
}
